#!/usr/bin/env python3
"""Initialize, generate, and validate OWL project memory."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Iterable

OWL_FILES = ("OUTLINE.md", "WISDOM.md", "LEGACY.md")
EXCLUDED_PARTS = {".git", "__pycache__", ".venv", ".pytest_cache"}
TEXT_SUFFIXES = {".md", ".json", ".py", ".yml", ".yaml", ".txt", ""}
SELF_MARKER = Path("control/owl.json")


class OwlError(Exception):
    pass


def fail(message: str) -> None:
    raise OwlError(message)


def read_text(path: Path) -> str:
    try:
        raw = path.read_bytes()
    except FileNotFoundError:
        fail(f"missing required file: {path}")
    if b"\r" in raw:
        fail(f"{path}: line endings must be LF")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        fail(f"{path}: file must be UTF-8 text")
    if text and not text.endswith("\n"):
        fail(f"{path}: file must end with a newline")
    return text


def section_names(text: str) -> set[str]:
    return {line[3:].strip() for line in text.splitlines() if line.startswith("## ")}


def section_body(text: str, name: str) -> str:
    marker = f"## {name}\n"
    if marker not in text:
        return ""
    return text.split(marker, 1)[1].split("\n## ", 1)[0].strip()


def validate_project(root: Path) -> list[str]:
    messages: list[str] = []
    for name in OWL_FILES:
        text = read_text(root / name)
        if not text.startswith("# "):
            fail(f"{name}: first line must be a level-one heading")
        messages.append(f"PASS: {name} exists and is readable")

    outline = read_text(root / "OUTLINE.md")
    required = {
        "Current objective",
        "Verified current state",
        "Active work",
        "Next action",
        "Unresolved",
    }
    missing = sorted(required - section_names(outline))
    if missing:
        fail(f"OUTLINE.md: missing sections: {', '.join(missing)}")

    for name in ("Current objective", "Verified current state", "Next action"):
        if not section_body(outline, name):
            fail(f"OUTLINE.md: '{name}' must not be empty")

    messages.append("PASS: OUTLINE.md contains the continuity handoff fields")
    return messages


def load_manifest(root: Path) -> dict:
    path = root / SELF_MARKER
    try:
        data = json.loads(read_text(path))
    except json.JSONDecodeError as exc:
        fail(f"{path}: invalid JSON: {exc}")
    required = {"name", "version", "canonical_files", "generated_files", "file_summaries"}
    missing = sorted(required - data.keys())
    if missing:
        fail(f"{path}: missing keys: {', '.join(missing)}")
    return data


def verify_file_set(root: Path, manifest: dict) -> list[str]:
    declared = set(manifest["canonical_files"]) | set(manifest["generated_files"])
    actual: set[str] = set()

    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in EXCLUDED_PARTS for part in path.parts):
            continue
        actual.add(path.relative_to(root).as_posix())

    missing = sorted(declared - actual)
    unexpected = sorted(actual - declared)
    if missing:
        fail("manifest declares missing files: " + ", ".join(missing))
    if unexpected:
        fail("unclassified files: " + ", ".join(unexpected))
    return sorted(declared)


def make_map(manifest: dict) -> str:
    paths = sorted(set(manifest["canonical_files"]) | set(manifest["generated_files"]))
    tree: dict = {}
    for rel in paths:
        node = tree
        for part in rel.split("/"):
            node = node.setdefault(part, {})

    lines = [
        "# Repository Map",
        "",
        "Generated by `python scripts/owl.py generate .`. Do not edit manually.",
        "",
        "```text",
        ".",
    ]

    def walk(node: dict, prefix: str = "") -> None:
        names = sorted(node)
        for index, name in enumerate(names):
            last = index == len(names) - 1
            lines.append(f"{prefix}{'└── ' if last else '├── '}{name}")
            if node[name]:
                walk(node[name], prefix + ("    " if last else "│   "))

    walk(tree)
    lines += ["```", "", "## File purposes", ""]

    for rel in paths:
        summary = manifest["file_summaries"].get(rel)
        if not summary:
            fail(f"control/owl.json: missing file summary for {rel}")
        role = "generated" if rel in manifest["generated_files"] else "source"
        lines.append(f"- `{rel}` — **{role}.** {summary}")

    return "\n".join(lines) + "\n"


def make_landing_pad(root: Path, manifest: dict) -> str:
    excluded = set(manifest.get("landing_pad_exclude", []))
    included = [
        rel for rel in sorted(manifest["canonical_files"] + manifest["generated_files"])
        if rel not in excluded
    ]

    lines = [
        "# owlbox Landing Pad",
        "",
        "Generated from repository sources. It introduces no new authority or facts.",
        "",
        "## Index",
        "",
        *[f"- `{rel}`" for rel in included],
        "",
    ]

    for rel in included:
        text = make_map(manifest) if rel == "MAP.md" else read_text(root / rel)
        lines += [f"## FILE: {rel}", "", "```text", text.rstrip("\n"), "```", ""]

    return "\n".join(lines)


def generate(root: Path) -> list[str]:
    manifest = load_manifest(root)
    (root / "MAP.md").write_text(make_map(manifest), encoding="utf-8", newline="\n")
    (root / "LANDING_PAD.md").write_text(
        make_landing_pad(root, manifest), encoding="utf-8", newline="\n"
    )
    return ["PASS: MAP.md generated", "PASS: LANDING_PAD.md generated"]


def validate_self(root: Path) -> list[str]:
    manifest = load_manifest(root)
    messages = validate_project(root)
    paths = verify_file_set(root, manifest)

    for rel in paths:
        path = root / rel
        if path.suffix in TEXT_SUFFIXES:
            read_text(path)
    messages.append("PASS: repository file set matches control/owl.json")

    if read_text(root / "MAP.md") != make_map(manifest):
        fail("MAP.md is stale; run: python scripts/owl.py generate .")
    if read_text(root / "LANDING_PAD.md") != make_landing_pad(root, manifest):
        fail("LANDING_PAD.md is stale; run: python scripts/owl.py generate .")
    messages.append("PASS: generated views match repository sources")

    banned = tuple("".join(map(chr, codes)) for codes in ((67,104,97,116,71,80,84),(67,108,97,117,100,101),(71,80,84)))
    for rel in manifest["canonical_files"]:
        text = read_text(root / rel)
        for term in banned:
            if term.casefold() in text.casefold():
                fail(f"{rel}: vendor or model-specific term is not allowed: {term}")
    messages.append("PASS: canonical sources are vendor-neutral")
    return messages


def init_project(root: Path, force: bool) -> list[str]:
    template_root = Path(__file__).resolve().parent.parent / "templates"
    root.mkdir(parents=True, exist_ok=True)
    created = []

    for name in OWL_FILES:
        target = root / name
        if target.exists() and not force:
            continue
        shutil.copyfile(template_root / name, target)
        created.append(name)

    return [
        "PASS: created " + ", ".join(created)
        if created
        else "PASS: OWL files already exist; nothing changed"
    ]


def print_messages(messages: Iterable[str]) -> None:
    for message in messages:
        print(message)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)

    init_cmd = commands.add_parser("init")
    init_cmd.add_argument("path", nargs="?", default=".")
    init_cmd.add_argument("--force", action="store_true")

    for name in ("generate", "validate", "check"):
        cmd = commands.add_parser(name)
        cmd.add_argument("path", nargs="?", default=".")

    args = parser.parse_args(argv)
    root = Path(args.path).resolve()

    try:
        if args.command == "init":
            messages = init_project(root, args.force)
        elif args.command == "generate":
            if not (root / SELF_MARKER).exists():
                fail("generate applies only to the owlbox source repository")
            messages = generate(root)
        elif args.command == "validate":
            messages = validate_self(root) if (root / SELF_MARKER).exists() else validate_project(root)
        elif args.command == "check":
            messages = (
                generate(root) + validate_self(root)
                if (root / SELF_MARKER).exists()
                else validate_project(root)
            )
        else:
            fail(f"unknown command: {args.command}")

        print_messages(messages)
        print("OWL CHECK PASSED")
        return 0
    except OwlError as exc:
        print(f"OWL CHECK FAILED: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
